# Workflow derived from https://github.com/rstudio/shiny-workflows
#
# NOTE: This Shiny team GHA workflow is overkill for most R packages.
# For most R packages it is better to use https://github.com/r-lib/actions
on:
  push:
    branches: [main, rc-**]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 8 * * 1" # every monday

name: Package checks

jobs:
  pkgdown:
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GHA_PAT }}

    steps:
      - name: Checkout GitHub repo
        uses: rstudio/shiny-workflows/.github/internal/checkout@v1

      - name: Install R, system dependencies, and package dependencies
        uses: rstudio/shiny-workflows/setup-r-package@v1
        with:
          pandoc-version: ${{ inputs.pandoc-version }}
          cache-version: ${{ inputs.cache-version }}
          needs: website
          extra-packages: |
            any::pkgdown
            any::testthat
            local::.
            ${{ inputs.extra-packages }}
      - name: Run 'website' script
        uses: rstudio/shiny-workflows/.github/internal/run-local-script@v1
        with:
          name: website

      - name: Verify index reference (PR)
        if: github.event_name != 'push'
        uses: rstudio/shiny-workflows/.github/internal/verify-pkgdown@v1
        with:
          check-title: ${{ inputs.check-title }}

      - name: Setup git (push)
        uses: rstudio/shiny-workflows/.github/internal/setup-git@v1

      - name: Build and deploy pkgdown site (push)
        if: github.event_name == 'push'
        shell: Rscript {0}
        run: |
          if ("${{inputs.check-title}}" == "false") options(rmarkdown.html_vignette.check_title = FALSE)
          pkgdown::deploy_to_branch(new_process = FALSE, clean = (${{ inputs.clean }}) )

  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          # - {os: macOS-latest,   r: 'release'}
          - { os: windows-latest, r: "release" }
          - { os: ubuntu-latest, r: "devel", http-user-agent: "release" }
          - { os: ubuntu-latest, r: "release" }
          - { os: ubuntu-latest, r: "oldrel-1" }

    env:
      GITHUB_PAT: ${{ secrets.GHA_PAT }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
